# Generated by Django 4.1.1 on 2022-10-02 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('protein_content', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.DecimalValidator(5, 1)])),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.DecimalValidator(5, 1)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.DecimalValidator(5, 2)])),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0), django.core.validators.DecimalValidator(5, 1)])),
                ('review', models.TextField(max_length=500)),
            ],
        ),
    ]
