# Generated by Django 4.1.1 on 2022-10-10 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_whey_price_alter_whey_protein_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Rating Date')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('review', models.CharField(choices=[('E', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('A', 'Average'), ('B', 'Bad'), ('VB', 'Very Bad'), ('S', 'Stay Away')], default='A', max_length=2)),
                ('review_text', models.TextField(max_length=500)),
                ('whey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.whey')),
            ],
        ),
    ]
