# Generated by Django 4.1.1 on 2022-10-10 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_costumerrating_customerrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrating',
            name='date',
        ),
        migrations.AddField(
            model_name='customerrating',
            name='rating_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Rating Date'),
        ),
    ]
