# Generated by Django 4.1.1 on 2022-10-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_customerrating_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrating',
            old_name='rating_date',
            new_name='date',
        ),
    ]
