# Generated by Django 4.1.1 on 2022-10-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_customerrating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrating',
            name='value',
            field=models.CharField(choices=[('E', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('A', 'Average'), ('B', 'Bad'), ('VB', 'Very Bad'), ('S', 'Stay Away')], max_length=2),
        ),
    ]
