# Generated by Django 4.1.1 on 2022-10-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_celebrity_whey_celebrities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('whey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.whey')),
            ],
        ),
    ]
